#!/usr/bin/bash

PROGRAMAS_PARA_INSTALAR=(
  links
  wget
)

# Instalar programas no apt
for nome_do_programa in ${PROGRAMAS_PARA_INSTALAR[@]}; do
  if ! yum list | grep -q $nome_do_programa; then # Só instala se já não estiver instalado
    yum install "$nome_do_programa" -y
  else
    echo "[INSTALADO] - $nome_do_programa"
  fi
done
